spring:
  config:
    import:
      - config/datasource.yml
      - config/oauth.yml
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    root: INFO
    com.ll.gramgram: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
